### ISSUE TITLE
Not Compatible with below 21 API android

### ISSUE THREAD

**Issue by Harshdeep4295** [ChaosLeong/PinView#22]
I tried to run my application with this pin view layout in the tablet with version 4.4.2 and it goes break off i.e., a message pop up with "Unfortunately, it stops working."

**Comment by ChaosLeong** [comment]
Can you please provide crash log?

**Comment by Harshdeep4295** [comment]
Please find below : -

 Caused by: android.view.InflateException: Binary XML file line #91: Error inflating class com.chaos.view.PinView
                      at android.view.LayoutInflater.createView(LayoutInflater.java:620)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                      at com.prologicfirst.touche.fragment.FragmentLogin.onCreateView(FragmentLogin.java:102)
                      at android.app.Fragment.performCreateView(Fragment.java:1700)
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
                      at android.app.BackStackRecord.run(BackStackRecord.java:684)
                      at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
                      at android.app.Activity.performStart(Activity.java:5240)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2157)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233) 
                      at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:136) 
                      at android.app.ActivityThread.main(ActivityThread.java:5001) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                      at dalvik.system.NativeStart.main(Native Method) 
                   Caused by: java.lang.reflect.InvocationTargetException
                      at java.lang.reflect.Constructor.constructNative(Native Method)
                      at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                      at android.view.LayoutInflater.createView(LayoutInflater.java:594)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                      at com.prologicfirst.touche.fragment.FragmentLogin.onCreateView(FragmentLogin.java:102) 
                      at android.app.Fragment.performCreateView(Fragment.java:1700) 
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890) 
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062) 
                      at android.app.BackStackRecord.run(BackStackRecord.java:684) 
                      at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447) 
                      at android.app.Activity.performStart(Activity.java:5240) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2157) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233) 
                      at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:136) 
                      at android.app.ActivityThread.main(ActivityThread.java:5001) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                      at dalvik.system.NativeStart.main(Native Method) 
                   Caused by: android.content.res.Resources$NotFoundException: Resource is not a ColorStateList (color or path): TypedValue{t=0x2/d=0x7f04006f a=2}
                      at android.content.res.Resources.loadColorStateList(Resources.java:2237)
                      at android.content.res.TypedArray.getColorStateList(TypedArray.java:343)
                      at android.widget.TextView.<init>(TextView.java:960)
                      at android.widget.EditText.<init>(EditText.java:60)
                      at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:64)
                      at com.chaos.view.PinView.<init>(PinView.java:108)
                      at com.chaos.view.PinView.<init>(PinView.java:104)
                      at java.lang.reflect.Constructor.constructNative(Native Method) 
                      at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                      at android.view.LayoutInflater.createView(LayoutInflater.java:594) 
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                      at com.prologicfirst.touche.fragment.FragmentLogin.onCreateView(FragmentLogin.java:102) 
                      at android.app.Fragment.performCreateView(Fragment.java:1700) 
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890) 
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062) 
                      at android.app.BackStackRecord.run(BackStackRecord.java:684) 
                      at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447) 
                      at android.app.Activity.performStart(Activity.java:5240) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2157) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233) 
                      at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:136) 
                      at android.app.ActivityThread.main(ActivityThread.java:5001) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                      at dalvik.system.NativeStart.main(Native Method)

**Comment by ChaosLeong** [comment]
Can you please show your xml code? And the device information

**Comment by Harshdeep4295** [comment]
please Check the log file... 
[fragment_login.log](https://github.com/ChaosLeong/PinView/files/2200648/fragment_login.log)

**Comment by ChaosLeong** [comment]
I tried with your xml code, but nothing happened. Can you provide a demo that can reproduce this bug?

**Comment by Harshdeep4295** [comment]
Demo as in what should I provide you with? since my first activity contains this fragment whenever I launch the app it crashes. You can check this code of Java file.

**Comment by ChaosLeong** [comment]
@Harshdeep4295 Sorry for the delayed response. Because PinView inherits from AppCompatEditText, therefore you must use Theme.AppCompat.

**Comment by Harshdeep4295** [comment]
@ChaosLeong Can we make changes to project as to provide backward compatibility?

**Comment by imansdn** [comment]
in my case the reason was using standard dimen sdp and ssp units like @dimen/_13sdp !
